title: Welcome to my personal blog!
author: Ariel C
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  My what do I say in my first blog post, I'm nervous to be honest.
  Well, hello... I guess.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
